/*
 * MMS Example API
 *
 * Documentation for MMS API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PermissionLookup struct {
	Type_             string `json:"type,omitempty"`
	OrgId             string `json:"orgId,omitempty"`
	ProjectId         string `json:"projectId,omitempty"`
	RefId             string `json:"refId,omitempty"`
	Privilege         string `json:"privilege,omitempty"`
	AllowAnonIfPublic bool   `json:"allowAnonIfPublic,omitempty"`
	HasPrivilege      bool   `json:"hasPrivilege,omitempty"`
}
