/*
 * MMS Example API
 *
 * Documentation for MMS API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PermissionUpdatesResponse struct {
	Inherit bool                      `json:"inherit,omitempty"`
	Users   *PermissionUpdateResponse `json:"users,omitempty"`
	Groups  *PermissionUpdateResponse `json:"groups,omitempty"`
	Public  bool                      `json:"public,omitempty"`
}
