/*
 * MMS Example API
 *
 * Documentation for MMS API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PermissionUpdate struct {
	Action      string `json:"action,omitempty"`
	Name        string `json:"name,omitempty"`
	Role        string `json:"role,omitempty"`
	OrgId       string `json:"orgId,omitempty"`
	OrgName     string `json:"orgName,omitempty"`
	ProjectId   string `json:"projectId,omitempty"`
	ProjectName string `json:"projectName,omitempty"`
	BranchId    string `json:"branchId,omitempty"`
	Inherited   bool   `json:"inherited,omitempty"`
}
