/*
 * MMS Example API
 *
 * Documentation for MMS API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BasicSearchRequest struct {
	Params  map[string]string `json:"params,omitempty"`
	Recurse map[string]string `json:"recurse,omitempty"`
	From    int32             `json:"from,omitempty"`
	Size    int32             `json:"size,omitempty"`
}
