/*
 * MMS Example API
 *
 * Documentation for MMS API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PermissionsResponse struct {
	Inherit bool                `json:"inherit,omitempty"`
	Users   *PermissionResponse `json:"users,omitempty"`
	Groups  *PermissionResponse `json:"groups,omitempty"`
	Public  bool                `json:"public,omitempty"`
}
