/*
 * MMS Example API
 *
 * Documentation for MMS API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PermissionsRequest struct {
	Users   *PermissionUpdateRequest `json:"users,omitempty"`
	Groups  *PermissionUpdateRequest `json:"groups,omitempty"`
	Inherit bool                     `json:"inherit,omitempty"`
	Public  bool                     `json:"public,omitempty"`
}
