/*
 * MMS Example API
 *
 * Documentation for MMS API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Permission struct {
	Name string `json:"name,omitempty"`

	Role string `json:"role,omitempty"`
}
