/*
 * MMS Example API
 *
 * Documentation for MMS API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"CreateOrUpdateArtifacts",
		strings.ToUpper("Post"),
		"/projects/{projectId}/refs/{refId}/elements/{elementId}",
		CreateOrUpdateArtifacts,
	},

	Route{
		"DeleteArtifactByExtension",
		strings.ToUpper("Delete"),
		"/projects/{projectId}/refs/{refId}/elements/{elementId}/{extension}",
		DeleteArtifactByExtension,
	},

	Route{
		"GetArtifactByExtension",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/elements/{elementId}/{extension}",
		GetArtifactByExtension,
	},

	Route{
		"CheckAuthenticationToken",
		strings.ToUpper("Get"),
		"/checkAuth",
		CheckAuthenticationToken,
	},

	Route{
		"CreateAuthenticationToken",
		strings.ToUpper("Post"),
		"/authentication",
		CreateAuthenticationToken,
	},

	Route{
		"CreateUser",
		strings.ToUpper("Post"),
		"/user",
		CreateUser,
	},

	Route{
		"GetAuthenticationToken",
		strings.ToUpper("Get"),
		"/authentication",
		GetAuthenticationToken,
	},

	Route{
		"GetBranchPermissions",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/permissions",
		GetBranchPermissions,
	},

	Route{
		"GetOrgPermissions",
		strings.ToUpper("Get"),
		"/orgs/{orgId}/permissions",
		GetOrgPermissions,
	},

	Route{
		"GetProjectPermissions",
		strings.ToUpper("Get"),
		"/projects/{projectId}/permissions",
		GetProjectPermissions,
	},

	Route{
		"GetUsers",
		strings.ToUpper("Get"),
		"/users",
		GetUsers,
	},

	Route{
		"LookupPermissions",
		strings.ToUpper("Put"),
		"/permissions",
		LookupPermissions,
	},

	Route{
		"UpdateBranchPermissions",
		strings.ToUpper("Post"),
		"/projects/{projectId}/refs/{refId}/permissions",
		UpdateBranchPermissions,
	},

	Route{
		"UpdateOrgPermissions",
		strings.ToUpper("Post"),
		"/orgs/{orgId}/permissions",
		UpdateOrgPermissions,
	},

	Route{
		"UpdatePassword",
		strings.ToUpper("Post"),
		"/password",
		UpdatePassword,
	},

	Route{
		"UpdateProjectPermissions",
		strings.ToUpper("Post"),
		"/projects/{projectId}/permissions",
		UpdateProjectPermissions,
	},

	Route{
		"GetCommit",
		strings.ToUpper("Get"),
		"/projects/{projectId}/commits/{commitId}",
		GetCommit,
	},

	Route{
		"GetCommits",
		strings.ToUpper("Put"),
		"/projects/{projectId}/commits",
		GetCommits,
	},

	Route{
		"GetElementCommits",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/elements/{elementId}/commits",
		GetElementCommits,
	},

	Route{
		"GetRefCommits",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/commits",
		GetRefCommits,
	},

	Route{
		"CreateOrUpdateElements",
		strings.ToUpper("Post"),
		"/projects/{projectId}/refs/{refId}/elements",
		CreateOrUpdateElements,
	},

	Route{
		"DeleteElement",
		strings.ToUpper("Delete"),
		"/projects/{projectId}/refs/{refId}/elements/{elementId}",
		DeleteElement,
	},

	Route{
		"DeleteElements",
		strings.ToUpper("Delete"),
		"/projects/{projectId}/refs/{refId}/elements",
		DeleteElements,
	},

	Route{
		"GetAllElements",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/elements",
		GetAllElements,
	},

	Route{
		"GetArtifactForElement1",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/elements/{elementId}",
		GetArtifactForElement1,
	},

	Route{
		"GetElements",
		strings.ToUpper("Put"),
		"/projects/{projectId}/refs/{refId}/elements",
		GetElements,
	},

	Route{
		"CreateLocalGroup",
		strings.ToUpper("Put"),
		"/groups/{group}",
		CreateLocalGroup,
	},

	Route{
		"DeleteLocalGroup",
		strings.ToUpper("Delete"),
		"/groups/{group}",
		DeleteLocalGroup,
	},

	Route{
		"GetAllGroups",
		strings.ToUpper("Get"),
		"/groups",
		GetAllGroups,
	},

	Route{
		"GetGroup",
		strings.ToUpper("Get"),
		"/groups/{group}",
		GetGroup,
	},

	Route{
		"UpdateGroupUsers",
		strings.ToUpper("Post"),
		"/groups/{group}/users",
		UpdateGroupUsers,
	},

	Route{
		"Healthcheck",
		strings.ToUpper("Get"),
		"/healthcheck",
		Healthcheck,
	},

	Route{
		"CreateOrUpdateNotebooks",
		strings.ToUpper("Post"),
		"/projects/{projectId}/refs/{refId}/notebooks",
		CreateOrUpdateNotebooks,
	},

	Route{
		"GetAllNotebooks",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/notebooks",
		GetAllNotebooks,
	},

	Route{
		"GetNotebook",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/notebooks/{notebookId}",
		GetNotebook,
	},

	Route{
		"GetNotebooks",
		strings.ToUpper("Put"),
		"/projects/{projectId}/refs/{refId}/notebooks",
		GetNotebooks,
	},

	Route{
		"CreateOrUpdateOrgs",
		strings.ToUpper("Post"),
		"/orgs",
		CreateOrUpdateOrgs,
	},

	Route{
		"DeleteOrg",
		strings.ToUpper("Delete"),
		"/orgs/{orgId}",
		DeleteOrg,
	},

	Route{
		"GetAllOrgs",
		strings.ToUpper("Get"),
		"/orgs",
		GetAllOrgs,
	},

	Route{
		"GetOrg",
		strings.ToUpper("Get"),
		"/orgs/{orgId}",
		GetOrg,
	},

	Route{
		"CreateOrUpdateProjects",
		strings.ToUpper("Post"),
		"/projects",
		CreateOrUpdateProjects,
	},

	Route{
		"DeleteProject",
		strings.ToUpper("Delete"),
		"/projects/{projectId}",
		DeleteProject,
	},

	Route{
		"GetAllProjects",
		strings.ToUpper("Get"),
		"/projects",
		GetAllProjects,
	},

	Route{
		"GetProject",
		strings.ToUpper("Get"),
		"/projects/{projectId}",
		GetProject,
	},

	Route{
		"GetProjectSchemaOptions",
		strings.ToUpper("Get"),
		"/schemas",
		GetProjectSchemaOptions,
	},

	Route{
		"CreateRefs",
		strings.ToUpper("Post"),
		"/projects/{projectId}/refs",
		CreateRefs,
	},

	Route{
		"DeleteRef",
		strings.ToUpper("Delete"),
		"/projects/{projectId}/refs/{refId}",
		DeleteRef,
	},

	Route{
		"GetAllRefs",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs",
		GetAllRefs,
	},

	Route{
		"GetRef",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}",
		GetRef,
	},

	Route{
		"GetBasicSearch",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/search",
		GetBasicSearch,
	},

	Route{
		"PostBasicSearch",
		strings.ToUpper("Post"),
		"/projects/{projectId}/refs/{refId}/search",
		PostBasicSearch,
	},

	Route{
		"CreateOrUpdateViews",
		strings.ToUpper("Post"),
		"/projects/{projectId}/refs/{refId}/views",
		CreateOrUpdateViews,
	},

	Route{
		"GetDocuments",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/documents",
		GetDocuments,
	},

	Route{
		"GetGroups",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/groups",
		GetGroups,
	},

	Route{
		"GetMounts",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/mounts",
		GetMounts,
	},

	Route{
		"GetView",
		strings.ToUpper("Get"),
		"/projects/{projectId}/refs/{refId}/views/{viewId}",
		GetView,
	},

	Route{
		"GetViews",
		strings.ToUpper("Put"),
		"/projects/{projectId}/refs/{refId}/views",
		GetViews,
	},

	Route{
		"CreateOrUpdateWebhooks",
		strings.ToUpper("Post"),
		"/projects/{projectId}/webhooks",
		CreateOrUpdateWebhooks,
	},

	Route{
		"DeleteWebhooks",
		strings.ToUpper("Delete"),
		"/projects/{projectId}/webhooks",
		DeleteWebhooks,
	},

	Route{
		"GetAllWebhooks",
		strings.ToUpper("Get"),
		"/projects/{projectId}/webhooks",
		GetAllWebhooks,
	},
}
